version: "1"
services:
  db:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
  app:
    container_name: mongodb-test
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db